sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
before_script:
  - npm run build
cache:
    directories:
      - node_modules
deploy:
  skip-cleanup: true
  keep-history: true
  provider: pages
  local-dir: dist
